FROM node:12.14.0-alpine3.11

RUN apk add --no-cache openssl

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY . .

COPY --chown=node ./ .

RUN npm i -g @nestjs/cli@7.4.1

RUN npm install

RUN npm run build

CMD ["npm", "run", "start:prod"]
