version: '3'

services:

  app:
    image: "12.18.3"
    container_name: nest-app
    build: 
      context: .
      dockerfile: Dockerfile.prod
    entrypoint:  ./.docker/entrypoint.sh
    
    
    ports:
      - 3000:3000
    
     
    

  

