version: '3'

services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    entrypoint:  npm run start:prod
    container_name: nest-app
    
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    

  

