name: CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: docker-compose -f docker-compose.prod.yaml up -d
            - run: docker exec nest-app dockerize -timeout=200s -wait=http://localhost:3000
            - run: docker exec nest-app npm run test
